### PR TITLE
Support mass rendering

### LINKED ISSUE #36: support "mass" rendering
If I have a lot of templates and I want to render all of them with the same context It may be useful to convert the parameter into JSON once and use it on every templates. That would spare a `to_string()` in `renderw()`.

If you are open for this feature I think I can contribute it.

### PR DESCRIPTION
**Pull request by ihrwein**
Fixes #36 

I'd like to write some tests for it before you merge.

### CODE REVIEW

**Comment by sunng87** [comment]
Hi @ihrwein , thanks for this patch and your effort. Instead of providing a `RendererIterator`, I think giving user the `get_templates().iter()` is more flexible in general. For example, they can use `map(...)` to render or add a `filter(...)` for selective rendering. The `RenderIterator` seems a little duplicated to template iterator and can be implemented outside the core library.

The issue you pointed out in #36 is some useless `clone()` when calling `render()` multiple times. So I think we should focus on that issue by providing a `render()` with `Json` type as data. 

WDYT?

**Comment by ihrwein** [comment]
You are right, I was too eager to solve this. How would you call the new function? We may also need a new constuctor for `Context` which takes ownership of a `Json` value (If I'm correct).

**Comment by sunng87** [comment]
True, perhaps we need to change `Context` to hold a `&Json` instead of a clone in current impl. 

Also I'm thinking about a break change to `renderw`. We can change `renderw` to accept data as `&Json`. And leave `render()` as a convenience shortcut, unchanged.

**Comment by sunng87** [comment]
Changing `Context` to `Context<'a> { data: &'a Json}` seems expensive. Especially we have function like `extend` that will create new `Context`. 

A simpler approach is to use `Context` as parameter in `renderw`. User could construct a `Context` and reuse it in the iterator.

**Comment by ihrwein** [comment]
That would be fine for me. Should I make a pull request?

**Comment by sunng87** [comment]
@ihrwein Will be great if you would :-) Thanks!

**Comment by ihrwein** [comment]
I sent a new PR. Should I close this one so we can move to the new one with the conversation and review?

**Comment by sunng87** [comment]
Thanks for your patient. I will close this one.

**Pull request closed without merging**
