### PR TITLE
fix(#666): Add builder for non-exhaustive structs

### PR DESCRIPTION
**Pull request by hadizamani021**
Dear sunng,
For issue (#666): If you are okay with this type of builder, please let me add it for the other non-exhaustive structs. If there are any issues, let me know so I can fix them before proceeding to add it to the other structs.

### CODE REVIEW

**Comment by sunng87** [comment]
@hadizamani021 Thank you! You can use `derive_builder` crate to generate builders for this case.

**Comment by sunng87** [comment]
LGTM. Is there any other struct to add builder?

**Review by sunng87 — APPROVED** [review]

**Comment by hadizamani021** [comment]
@sunng87 Thank you sunng, I added for all non_exhaustive structs.

**Comment by sunng87** [comment]
@hadizamani021 Thank you!

**Pull request merged**
