### PR TITLE
updated serde to v1

### PR DESCRIPTION
**Pull request by skariel**
see #149

### CODE REVIEW

**Comment by SergioBenitez** [comment]
@skariel The build has failed.

**Comment by sunng87** [comment]
Serde-json had some breaking change and the `ToJson` trait we have been relied on is removed.
Seems we need to use the `Serialize` trait instead.

**Comment by sunng87** [comment]
More information: https://github.com/serde-rs/json/issues/294

**Comment by euclio** [comment]
This might be an opportunity to remove `rustc-serialize` support entirely, now that it's officially deprecated.

**Comment by sunng87** [comment]
Yes the #141 has been there for a while. Now it's time to merge.

**Comment by sunng87** [comment]
@skariel Did you look into the failure and work on it? Some handlebars-rust internals might be involved in this update. So if you didn't start to work on it, I will create a new PR to fix everything.

**Comment by skariel** [comment]
@sunng87 I didn't start, you can go ahead :) Thanks!

**Comment by sunng87** [comment]
Nice, I will close this one.

**Pull request closed without merging**
